### ISSUE TITLE
Include Custom Directories in Build Sandbox

### ISSUE THREAD

**Issue by vbrandl** [tenx-tech/cargo2nix#103]
If a project depends on other files in the repository other than `src`, `Cargo.*` and any potential build scripts, e.g. a template directory, these are not included in the build sandbox and the build fails.

I prepared a testcase again (this time with everything pinned using `niv`): https://github.com/vbrandl/cargo2nix-ructe-testcase

It uses `ructe` for templating and the templates are located in the `templates` directory.

The build fails while evaluating the `build.rs` script.

Similar problems might happen when using tools like [`vergen`](https://github.com/rustyhorde/vergen) to include e.g. the commit hash at compile time, since it needs at least `.git` and it's contents.

Is there a way to include some (or all) files in the repository inside the build sandbox?

I don't know if this is actually an issue with cargo2nix or with me not knowing enough about nix expressions...

**Comment by ebkalderon** [comment]
Hey there, @vbrandl! This should already be possible using [`localPatterns`](https://github.com/tenx-tech/cargo2nix/blob/master/default.nix#L50). Apologies that we haven't gotten around to adding an example project showcasing it yet! I'm working on it. :sweat_smile: Does this resolve the issue for you?

**Comment by ebkalderon** [comment]
By default, we include the `src` and `tests` directories in their entirety plus all `.toml` and `.rs` files located at the project root ([source](https://github.com/tenx-tech/cargo2nix/blob/931c2fed7cc1df9670847a3af811b773b8cf11d7/overlay/make-package-set/full.nix#L15)). Clearly, this is working since the `build.rs` for your test case is being detected and evaluated.

It would be nice if we could utilize Cargo's native [`includes` and `excludes`](https://github.com/tenx-tech/cargo2nix/issues/36#issuecomment-591351632) in the project's `Cargo.toml` going forward, but implementing this isn't exactly trivial.

**Comment by ebkalderon** [comment]
By default, we include the `src` and `tests` directories in their entirety plus all `.toml` and `.rs` files located at the project root ([source](https://github.com/tenx-tech/cargo2nix/blob/931c2fed7cc1df9670847a3af811b773b8cf11d7/overlay/make-package-set/full.nix#L15)).

It would be nice if we could utilize Cargo's native [`includes` and `excludes`](https://github.com/tenx-tech/cargo2nix/issues/36#issuecomment-591351632) in the project's `Cargo.toml` going forward, but implementing this isn't exactly trivial, especially in a crate workspace with multiple `Cargo.toml` files to inspect.

**Comment by ebkalderon** [comment]
Since #105 has been merged and #106 has been opened, I think this issue should be safe to close. Hope the explanations were helpful!
