### ISSUE TITLE
Git Deps Support Broken

### ISSUE THREAD

**Issue by macs-overdrv** [tenx-tech/cargo2nix#108]
## First the Broken Parts

The overlay, necessary for consuming generated `Cargo.nix` currently contains broken references to `fetchgitPrivate`
https://github.com/tenx-tech/cargo2nix/blob/master/overlay/lib/fetch.nix#L11-L12

```shell
$ nix-channel --list
...
nixos https://nixos.org/channels/nixos-20.03

$ nix repl '<nixpkgs>'
nix-repl> buildPackages.fetchgitPrivate
error: attribute 'fetchgitPrivate' missing, at (string):1:1
```
`fetchgitPrivate` is actually [dead in master nixpkgs](https://github.com/NixOS/nixpkgs/commit/e578b8499f9e49441d9761875659381f95975fee)

## Crafting a Fix

There are three contexts to reconcile:

### Cargo
[Specifying dependencies from git repositories](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)
> Since we haven’t specified any other information, Cargo assumes that we intend to use the latest commit on the master branch to build our package. You can combine the git key with the *rev*, *tag*, or *branch* keys to specify something else.

Cargo lockfiles do not appear to include checksums for git dependencies.

### Cargo2Nix
https://github.com/tenx-tech/cargo2nix/blob/master/templates/Cargo.nix.tera#L49-L55

### Nix
`fetchgit` doesn't fetch at evaluation time
`fetchGit` doesn't accept a sha256 argument (this is being [calculated by cargo2nix](https://github.com/tenx-tech/cargo2nix/blob/master/src/main.rs#L553-L557) since it's not in the cargo docs.)
`fetchFromGitHub` will of course only work for Github

The most functionality will be covered by switching `fetchGit`.   The downside is that the sha256 argument needs to be ignored and no integrity check will be performed.  This sha256 pin & check may be possible for generic git, but the appropriate place for a fix would be upstream in nixpkgs, not in cargo2nix.

## Tracking Integrity Issues

I attempted to contextualize the choices within the Rust community and found Boats discussing [the update framework](https://theupdateframework.io/) https://github.com/rust-lang/cargo/issues/4768  I was unable to find an issue to add sha256 support to git fetchers generically in nixpkgs. Recommend adding tracking issues to this repo if other integrity check work is known.

**Comment by ebkalderon** [comment]
Thanks a lot for raising the issue, @macs-overdrv! :heart: We've known that `fetchgitPrivate` has been dead or dying in Nixpkgs for a while, but we haven't gotten around to officially switching over to `builtins.fetchGit`. Many thanks again for opening a pull request and doing the brunt of the work.

In theory, there should be no need for any additional hashing for Git crate dependencies, as the commit ref produced by the Git repo's Merkle tree should already be sufficient for this task. The computation of the `sha256` value for Git dependencies was only really to accommodate `fetchgitPrivate`, which required this (arguably redundant) argument. Now that `builtins.fetchGit` no longer requires it, the argument is no longer needed for `fetchCrateGit` as well.

I imagine that removing this argument would break compatibility with existing projects being used in the wild, however, requiring them to update both their `cargo2nix` overlays and the local CLI tool. We should be careful not to do this immediately to keep the transition as smooth as possible. I think we could have a transitional patch release which removes the `sha256` argument entirely from the Tera template and the Rust code, but we retain a dummy argument with a default value in the overlay for backwards compatibility with older `Cargo.nix` files.

**Comment by ebkalderon** [comment]
Another important thing to note is that `fetchCrateAlternateRegistryExpensive` requires an always up-to-date version of the index Git repo. Because `fetchgitPrivate` operates at build-time, this is never an issue, but @trha pointed out to me in discussions that with `builtins.fetchGit`, the index repo might be outdated, depending on how long Nix caches the impure fetch.

According to [this section in the Nix Manual](https://nixos.org/nix/manual/#idm140737321634320), the default `tarball-ttl` is 1 hour, so it might not be a huge deal for most organizations, given the typical update interval for many alternate registry sources. But either way, we should document adjusting `tarball-ttl` as a possible fix to any outdated alternate registry issues users might be facing.

Also, it appears that making impure `master` fetches with `builtins.fetchGit` doesn't work in pure evaluation mode, meaning that Cargo alternative registries will now be unsupported in pure mode. This is probably a reasonable enough sacrifice to make for forward compatibility, but it should still be documented somewhere as well.

**Comment by macs-overdrv** [comment]
> I imagine that removing this argument would break compatibility with existing projects being used in the wild

1. The PR just [declines to consume the argument](https://github.com/tenx-tech/cargo2nix/pull/109/files#diff-90ec9eaf8cb3ab0e99c8b076044f83d0L14)
2. If the argument was removed, removing the argument from the `Cargo.nix` would imply the user is generating with a newer version of Cargo2nix that also contains a newer overlay that can handle removing the argument.

We're good there.

> Because fetchgitPrivate operates
If the user is basing their project around a newer version of nixpkgs, even after including Cargo2nix's overlay, `fetchgitPrivate` no longer exists.  Either cargo2nix or the user need to provide it and will probably just take the easy road and wrap `fetchGit`

> tarball-ttl
Which has a definition that will be updated when the user _really_ wants a new version from their own registry, meaning the ttl will not affect the decision by nix to fetch.

I think we're good here.

**Comment by ebkalderon** [comment]
> 1. The PR just [declines to consume the argument](https://github.com/tenx-tech/cargo2nix/pull/109/files#diff-90ec9eaf8cb3ab0e99c8b076044f83d0L14)
> 2. If the argument was removed, removing the argument from the `Cargo.nix` would imply the user is generating with a newer version of Cargo2nix that also contains a newer overlay that can handle removing the argument.

Hmm, I'm not sure whether we should remove the `sha256` argument from the overlay immediately. I was initially considering the following:

1. Switch to `builtins.fetchGit` internally but retain the `sha256` argument in `fetchCrateGit` with a dummy value as a fallback. This would ensure that users who upgrade the overlay and/or tool would not need to immediately regenerate their `Cargo.nix` file.
2. Remove the code for the `sha256` argument from the Rust code and the Tera template. This way, the next time the user runs `cargo2nix -f` to update the `Cargo.nix` file for a project, projects would be able to gradually migrate upward to the new format at their own rate.

Since `cargo2nix` has semver guarantees to uphold, I was thinking that it would be best that we make the transition period as smooth as possible. Any thoughts on this?

> If the user is basing their project around a newer version of nixpkgs, even after including Cargo2nix's overlay, `fetchgitPrivate` no longer exists. Either `cargo2nix` or the user need to provide it and will probably just take the easy road and wrap `fetchGit`

I think we both want to switch to `builtins.fetchGit` as soon as possible. There is definitely no disagreement there. 😄 

> Which has a definition that will be updated when the user _really_ wants a new version from their own registry, meaning the ttl will not affect the decision by nix to fetch.

I'm not sure I understand. The comments regarding `tarball-ttl` from earlier are specifically geared towards `fetchCrateAlternateRegistryExpensive`, where we are essentially fetching `master` from the alternate registry index, always. This would theoretically look like the following inside the `fetchCrateAlternateRegistryExpensive`:

```nix
builtins.fetchGit { url = https://github.com/owner/some-registry-index.git; ref = "master"; }
```

My understanding of the `tarball-ttl` setting was that in the expression above, if the impure `ref` doesn't change, `builtins.fetchGit` would not attempt to fetch `master` again until the TTL expires. According to the Nix manual, this would be a span of 1 hour by default. Is this understanding incorrect?

In the case of the old setup, we avoided the `tarball-ttl` setting altogether by cloning at build-time rather than at evaluation time. If the understanding above is true, then under `builtins.fetchGit` with a non-zero `tarball-ttl`, we would presumably have some occasions where we are operating on an out-of-date copy of the registry index.

To be clear, this is not a deal-breaker, though; we should still switch to `builtins.fetchGit` either way. But we should also document in the "Common issues" section of the README or elsewhere that if you happen to run into cases where a specific crate version is definitely present in an alternate registry index, but the Nix build is insisting that it cannot be found, you should add `--option tarball-ttl 0` to their `nix-build` command to force the index repo to update.

Hope this makes sense. Please do correct me if my understanding of `tarball-ttl` is wrong, though!

**Comment by ebkalderon** [comment]
> 1. The PR just [declines to consume the argument](https://github.com/tenx-tech/cargo2nix/pull/109/files#diff-90ec9eaf8cb3ab0e99c8b076044f83d0L14)
> 2. If the argument was removed, removing the argument from the `Cargo.nix` would imply the user is generating with a newer version of Cargo2nix that also contains a newer overlay that can handle removing the argument.

Hmm, I'm not sure whether we should remove the `sha256` argument from the overlay immediately. I was initially considering the following:

> 1. Switch to `builtins.fetchGit` internally but retain the `sha256` argument in `fetchCrateGit` with a dummy value as a fallback. This would ensure that users who upgrade the overlay and/or tool would not need to immediately regenerate their `Cargo.nix` file.
> 2. Remove the code for the `sha256` argument from the Rust code and the Tera template. This way, the next time the user runs `cargo2nix -f` to update the `Cargo.nix` file for a project, projects would be able to gradually migrate upward to the new format at their own rate.

Since `cargo2nix` has semver guarantees to uphold, I was thinking that it would be best that we make the transition period as smooth as possible. Any thoughts on this?

> If the user is basing their project around a newer version of nixpkgs, even after including Cargo2nix's overlay, `fetchgitPrivate` no longer exists. Either `cargo2nix` or the user need to provide it and will probably just take the easy road and wrap `fetchGit`

I think we both want to switch to `builtins.fetchGit` as soon as possible. There is definitely no disagreement there. 😄 

> Which has a definition that will be updated when the user _really_ wants a new version from their own registry, meaning the ttl will not affect the decision by nix to fetch.

I'm not sure I understand. The comments regarding `tarball-ttl` from earlier are specifically geared towards `fetchCrateAlternateRegistryExpensive`, where we are essentially fetching `master` from the alternate registry index, always. This would theoretically look like the following inside the `fetchCrateAlternateRegistryExpensive`:

```nix
builtins.fetchGit { url = https://github.com/owner/some-registry-index.git; ref = "master"; }
```

My understanding of the `tarball-ttl` setting was that in the expression above, if the impure `ref` doesn't change, `builtins.fetchGit` would not attempt to fetch `master` again until the TTL expires. According to the Nix manual, this would be a span of 1 hour by default. Is this understanding incorrect?

In the case of the old setup, we avoided the `tarball-ttl` setting altogether by cloning at build-time rather than at evaluation time. If the understanding above is true, then under `builtins.fetchGit` with a non-zero `tarball-ttl`, we would presumably have some occasions where we are operating on an out-of-date copy of the registry index.

To be clear, this is not a deal-breaker, though; we should still switch to `builtins.fetchGit` either way. But we should also document in the "Common issues" section of the README or elsewhere that if you happen to run into cases where a specific crate version is definitely present in an alternate registry index, but the Nix build is insisting that it cannot be found, you should add `--option tarball-ttl 0` to their `nix-build` command to force the index repo to update.

Hope this makes sense. Please do correct me if my understanding of `tarball-ttl` is wrong, though!

**Comment by ebkalderon** [comment]
> 1. The PR just [declines to consume the argument](https://github.com/tenx-tech/cargo2nix/pull/109/files#diff-90ec9eaf8cb3ab0e99c8b076044f83d0L14)
> 2. If the argument was removed, removing the argument from the `Cargo.nix` would imply the user is generating with a newer version of Cargo2nix that also contains a newer overlay that can handle removing the argument.

Hmm, I'm not sure whether we should remove the `sha256` argument from the overlay immediately. I was initially considering the following:

1. Switch to `builtins.fetchGit` internally but retain the `sha256` argument in `fetchCrateGit` with a dummy value as a fallback. This would ensure that users who upgrade the overlay and/or tool would not need to immediately regenerate their `Cargo.nix` file.
2. Remove the code for the `sha256` argument from the Rust code and the Tera template. This way, the next time the user runs `cargo2nix -f` to update the `Cargo.nix` file for a project, projects would be able to gradually migrate upward to the new format at their own rate.

Since `cargo2nix` has semver guarantees to uphold, I was thinking that it would be best that we make the transition period as smooth as possible. Any thoughts on this?

> If the user is basing their project around a newer version of nixpkgs, even after including Cargo2nix's overlay, `fetchgitPrivate` no longer exists. Either `cargo2nix` or the user need to provide it and will probably just take the easy road and wrap `fetchGit`

I think we both want to switch to `builtins.fetchGit` as soon as possible. There is definitely no disagreement there. 😄 

> Which has a definition that will be updated when the user _really_ wants a new version from their own registry, meaning the ttl will not affect the decision by nix to fetch.

I'm not sure I understand. The comments regarding `tarball-ttl` from earlier are specifically geared towards `fetchCrateAlternateRegistryExpensive`, where we are essentially fetching `master` from the alternate registry index, always. This would theoretically look like the following inside the `fetchCrateAlternateRegistryExpensive`:

```nix
builtins.fetchGit { url = https://github.com/owner/some-registry-index.git; ref = "master"; }
```

My understanding of the `tarball-ttl` setting was that in the expression above, if the impure `ref` doesn't change, `builtins.fetchGit` would not attempt to fetch `master` again until the TTL expires. According to the Nix manual, this would be a span of 1 hour by default. Is this understanding incorrect?

In the case of the old setup, we avoided the `tarball-ttl` setting altogether by cloning at build-time rather than at evaluation time. If the understanding above is true, then under `builtins.fetchGit` with a non-zero `tarball-ttl`, we would presumably have some occasions where we are operating on an out-of-date copy of the registry index.

To be clear, this is not a deal-breaker, though; we should still switch to `builtins.fetchGit` either way. But we should also document in the "Common issues" section of the README or elsewhere that if you happen to run into cases where a specific crate version is definitely present in an alternate registry index, but the Nix build is insisting that it cannot be found, you should add `--option tarball-ttl 0` to their `nix-build` command to force the index repo to update.

Hope this makes sense. Please do correct me if my understanding of `tarball-ttl` is wrong, though!

**Comment by ebkalderon** [comment]
> 1. The PR just [declines to consume the argument](https://github.com/tenx-tech/cargo2nix/pull/109/files#diff-90ec9eaf8cb3ab0e99c8b076044f83d0L14)
> 2. If the argument was removed, removing the argument from the `Cargo.nix` would imply the user is generating with a newer version of Cargo2nix that also contains a newer overlay that can handle removing the argument.

Hmm, I'm not sure whether we should remove the `sha256` argument from the overlay immediately. I was initially considering the following:

1. Switch to `builtins.fetchGit` internally but retain the `sha256` argument in `fetchCrateGit` with a dummy value as a fallback. This would ensure that users who upgrade the overlay and/or tool would not need to immediately regenerate their `Cargo.nix` file.
2. Remove the code for the `sha256` argument from the Rust code and the Tera template. This way, the next time the user runs `cargo2nix -f` to update the `Cargo.nix` file for a project, projects would be able to gradually migrate upward to the new format at their own rate.

Since `cargo2nix` has semver guarantees to uphold, I was thinking that it would be best that we make the transition period as smooth as possible. Any thoughts on this?

> If the user is basing their project around a newer version of nixpkgs, even after including Cargo2nix's overlay, `fetchgitPrivate` no longer exists. Either `cargo2nix` or the user need to provide it and will probably just take the easy road and wrap `fetchGit`

I think we both want to switch to `builtins.fetchGit` as soon as possible. There is definitely no disagreement there. 😄 

> Which has a definition that will be updated when the user _really_ wants a new version from their own registry, meaning the ttl will not affect the decision by nix to fetch.

I'm not sure I understand. The comments regarding `tarball-ttl` from earlier are specifically geared towards `fetchCrateAlternateRegistryExpensive`, where we are essentially fetching `master` from the alternate registry index, always. This would theoretically look like the following inside the `fetchCrateAlternateRegistryExpensive`:

```nix
builtins.fetchGit { url = https://github.com/owner/some-registry-index.git; ref = "master"; }
```

My understanding of the `tarball-ttl` setting was that in the expression above, if the impure `ref` doesn't change, `builtins.fetchGit` would not attempt to fetch `master` again until the TTL expires. According to the Nix manual, this would be a span of 1 hour by default. Is this understanding incorrect?

In the case of the old setup, we avoided the `tarball-ttl` setting altogether by cloning at build-time rather than at evaluation time. If the understanding above is true, then under `builtins.fetchGit` with a non-zero `tarball-ttl`, we would presumably have some occasions where we are operating on an out-of-date copy of the registry index.

To be clear, this is not a deal-breaker, though; we should still switch to `builtins.fetchGit` either way. But we should also document in the "Common issues" section of the README or elsewhere that if you happen to run into cases where a specific crate version is definitely present in an alternate registry index, but the Nix build is insisting that it cannot be found, you should add `--option tarball-ttl 0` to the `nix-build` command to force the index repo to update.

Hope this makes sense. Please do correct me if my understanding of `tarball-ttl` is wrong, though!

**Comment by macs-overdrv** [comment]
> Switch to builtins.fetchGit internally but retain the sha256 argument in fetchCrateGit with a dummy value as a fallback. This would ensure that users who upgrade the overlay and/or tool would not need to immediately regenerate their Cargo.nix file.

In the associated PR, the sha256 is retained and no regeneration is necessary. The overlay function is backwards compatible because it just ignores the argument.

> Since cargo2nix has semver guarantees to uphold, I was thinking that it would be best that we make the transition period as smooth as possible. Any thoughts on this?

There are no user-facing API changes. Existing pin files still work identically. These changes belong in the patch version.

In fact, since recent versions of nix already cannot consume the current cargo2nix overlay with deps outside of crates.io, it is the current version of cargo2nix that needs a disclaimer about compatible nix versions. While cargo2nix can be built with an outdated nixpkgs pin, the overlay necessary to consume the resulting `Cargo.nix` causes collisions between the two nix API versions of the project and cargo2nix.

There is an exception that is superseded by the above statement.  _Behavior_ changes transiently for alternative registry deps because of the under-specified uses of `fetchGit` that are forced to use a ttl instead of explicit updates to the `rev`. If the generated Cargo.nix contains no `rev` then it is not effectively pinning, which needs its own independent issue because the intended use cases of nix are exactly about reproducibility and durable dependency resolution. `tarball-ttl` has no place in an effective pinning strategy.

**Comment by ebkalderon** [comment]
> In the associated PR, the sha256 is retained and no regeneration is necessary. The overlay function is backwards compatible because it just ignores the argument.

Right, I just checked the source. Looks good for now! 

> There are no user-facing API changes. Existing pin files still work identically. These changes belong in the patch version.

Yeah, I think that approach should be fine for the time being. The next time that we release a new minor version, however, we should look at migrating pin files to have no `sha256` argument and use `..` in the overlay for temporary backwards compatibility until we can completely wean off of it. For the short term, I agree this should be perfectly fine to retain.

> needs a disclaimer about compatible nix versions

Agreed! We currently officially support the latest Nixpkgs stable, but this should be communicated more clearly in the README. 👍 

> If the generated `Cargo.nix` contains no `rev` then it is not effectively pinning, which needs its own independent issue because the intended use cases of nix are exactly about reproducibility and durable dependency resolution. `tarball-ttl` has no place in an effective pinning strategy.

I think maybe you are misunderstanding how Cargo alternate registries work in this case. The crate being fetched from the alternate registry is done so purely and is adequately pinned in the `Cargo.nix`. The checksum of the package, retrieved from the registry index Git repo, is reproducible and never changes because the registry. However, the registry index repo itself must necessarily be fetched impurely because that is how the alternate registry specification is fundamentally designed.

So if you have a private crate `foo:0.1.0` with checksum `1234567890abcdef` from `my-alt-registry` already vendored in the Nix store, the build is reproducible and pinned in the `Cargo.nix` with a `sha256` checksum (no relation to the `fetchgitPrivate` checksum). However, if the crate has never been fetched before, the latest index for `my-alt-registry` must be fetched impurely first, then crate `foo:0.1.0` with checksum `1234567890abcdef` is looked up, the crate data is fetched from the URL, and its integrity is verified against the checksum.
