### ISSUE TITLE
profilesByName emitting doesn't escape strings

### ISSUE THREAD

**Issue by philipstears** [tenx-tech/cargo2nix#120]
Howdy.

I tried adding:

```
[profile.release]
lto = "fat"
```

To my Cargo.toml, but when cargo2nix generates Cargo.nix, it emits:

```
   profilesByName = {
     release = builtins.fromTOML "lto = "fat"
 ";
   };
```

I'm unclear about the redundant new-line, but the main thing here is that the quotes inside of the TOML need escaping somehow, presumably before being passed to the template.

As a workaround, I'm able to use `lto = true` instead, but there are other potentially string-valued parameters that folks might want to change, for example the `panic` parameter.

**Comment by ebkalderon** [comment]
Hey there, @philipstears! Thanks for reporting this issue, and we're sorry you encountered it.

If you check the Tera templating code for `BuildPlan` in [`src/template.rs:33`](https://github.com/tenx-tech/cargo2nix/blob/827931a92dd92bea85856783ed95adf80517f9d8/src/template.rs#L33), the `profilesByName` entry values are computed by deserializing the Cargo profile struct into TOML using [`toml::ser::to_string()`](https://docs.rs/toml/0.5.6/toml/ser/fn.to_string.html). Unfortunately, the code wasn't rigorously tested, and it dumps the unsanitized TOML directly into a double-quoted Nix string, which causes the issues you saw. The trailing newline in the string is because `toml::ser::to_string()` apparently decided to insert one.

This bug should be fixable by calling `.replace("${", "\${").escape_debug()` on the output of `toml::ser::to_string()` to ensure that it's perfectly safe for the Nix expression to consume.

**Comment by ebkalderon** [comment]
I've opened https://github.com/tenx-tech/cargo2nix/pull/121 with a potential fix. It should be backwards-compatible with older versions of the overlay.

**Comment by philipstears** [comment]
Hey @ebkalderon - thank you so much!

**Comment by ebkalderon** [comment]
No worries! Hope this fix solves the problem in a satisfactory way. Feel free to test locally on your machine and leave any feedback on the PR itself.
