### ISSUE TITLE
Committing generated code

### ISSUE THREAD

**Issue by cryptoquick** [tenx-tech/cargo2nix#139]
My teammates are a bit reticent to commit what's essentially a generated file from a generated file. I can't explain to them why we shouldn't, so I figured I'd ask the maintainers, why do you commit the Cargo.nix in your repo when it could be generated from Cargo.lock?

**Comment by ebkalderon** [comment]
Good question, @cryptoquick! The reason why `cargo2nix` currently requires this is because the CLI tool relies on `cargo` itself to resolve features and generate the complete Nix build plan for the active Cargo workspace. This was chosen to be fully compatible out of the box with upstream Crates.io crates, without needing to reimplement all of Cargo's behavior ourselves, which changes frequently from version to version and has no formal specification. Cargo workspace resolution, as it is currently implemented in `cargo2nix`, requires access to the Internet and a writable `~/.cargo` directory which can be populated with registry index files. This means that `cargo2nix -f` cannot feasibly run inside the Nix sandbox, at present, which precludes on-the-fly generation of the `Cargo.nix` expression.

We do plan on adding support for import-from-derivation (see issue #87), which would enable on-the-fly generation of the `Cargo.nix` from within Nix itself, but there are some technical hurdles to overcome first. Outside contributions to this effort would be most welcome!

Hope this makes some sense. Thanks for asking!

**Comment by cryptoquick** [comment]
@ebkalderon Thank you for that explanation! And it does actually look like #87 would resolve the issue that had my teammates confused. I subscribed to that issue, and look forward to the day it lands. Unfortunately, I'm not yet experienced enough at Nix to take a crack at it, but who knows, ask me again in a year!

**Comment by ebkalderon** [comment]
Sounds great! Feel free to leave feedback or follow along with the other issue as you see fit. Any contribution you or your teammates can provide are welcome!
