### ISSUE TITLE
Cannot compile zmq and zmq-sys

### ISSUE THREAD

**Issue by bsima** [tenx-tech/cargo2nix#140]
Perhaps this is related to, or the same as, #130. 

Given the following repo and branch: https://github.com/bsima/rust-zmq/tree/cargo2nix-bug

We get `error: couldn't read build/main.rs: No such file or directory (os error 2)`

I believe the fix could be as simple as including the directory or file specified in the `build` directive from the Cargo.toml into the source tree when creating the derivation, but I'm not sure where this happens. If you can point me to the relevant code, I'd be happy to try and fix it.

I discovered this while trying to build a package that relies on `tmq`, which in turn relies on `zmq`. Maybe there is a way to fix this in the overlay, if so please advise, but I haven't been able to figure it out yet (aside: it would be helpful if `overlay/lib/overrides.nix` were exposed to the user, so I could just use your `makeOverride` function in my own overrides). 

In any case, I would think that cargo2nix should be able to handle these kinds of local dependencies, so I'm filing this as a bug.

<details>
<summary>Full shell output</summary>
<pre><code>
$ nix-build
these derivations will be built:
  /nix/store/c8rm5qxaxskgmv2mi538s8slb982pg03-crate-zmq-sys-0.11.0.drv
  /nix/store/f74yv9znnbicj2zw516ysf8l1n12ml57-crate-zmq-0.9.2.drv
building '/nix/store/c8rm5qxaxskgmv2mi538s8slb982pg03-crate-zmq-sys-0.11.0.drv'...
unpacking sources
unpacking source archive /nix/store/1sbmw2hab1bp3q4j7qh8nfzkk9kf8h92-source
source root is source
patching sources
configuring
building
   Compiling zmq-sys v0.11.0 (/private/var/folders/nk/rbcl1cjn7ljbgcfr04m_jyb40000gn/T/nix-build-crate-zmq-sys-0.11.0.drv-0/source)
{"reason":"compiler-message","package_id":"zmq-sys 0.11.0 (path+file:///private/var/folders/nk/rbcl1cjn7ljbgcfr04m_jyb40000gn/T/nix-build-crate-zmq-sys-0.11.0.drv-0/source)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-main","src_path":"/private/var/folders/nk/rbcl1cjn7ljbgcfr04m_jyb40000gn/T/nix-build-crate-zmq-sys-0.11.0.drv-0/source/build/main.rs","edition":"2015","doctest":false},"message":{"rendered":"error: couldn't read build/main.rs: No such file or directory (os error 2)\n\n","children":[],"code":null,"level":"error","message":"couldn't read build/main.rs: No such file or directory (os error 2)","spans":[]}}
{"reason":"compiler-message","package_id":"zmq-sys 0.11.0 (path+file:///private/var/folders/nk/rbcl1cjn7ljbgcfr04m_jyb40000gn/T/nix-build-crate-zmq-sys-0.11.0.drv-0/source)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-main","src_path":"/private/var/folders/nk/rbcl1cjn7ljbgcfr04m_jyb40000gn/T/nix-build-crate-zmq-sys-0.11.0.drv-0/source/build/main.rs","edition":"2015","doctest":false},"message":{"rendered":"error: aborting due to previous error\n\n","children":[],"code":null,"level":"error","message":"aborting due to previous error","spans":[]}}
{"reason":"build-finished","success":false}
error: could not compile `zmq-sys`.
To learn more, run the command again with --verbose.
builder for '/nix/store/c8rm5qxaxskgmv2mi538s8slb982pg03-crate-zmq-sys-0.11.0.drv' failed with exit code 101
cannot build derivation '/nix/store/f74yv9znnbicj2zw516ysf8l1n12ml57-crate-zmq-0.9.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/f74yv9znnbicj2zw516ysf8l1n12ml57-crate-zmq-0.9.2.drv' failed
</code>
</pre>
</details>

**Comment by ebkalderon** [comment]
Hello there, @bsima! It seems your `default.nix` is missing a `localPatterns` attribute which includes the `build` path at build time. Any files or directories outside of `src`, `tests`, and any `*.(rs|toml)` files at each individual crate's root are denied by default in `cargo2nix` to keep Nix derivation sizes as low as possible. See the [examples/3-static-resources](https://github.com/tenx-tech/cargo2nix/tree/master/examples/3-static-resources/) tutorial for details on how `localPatterns` works and how to whitelist additional files and directories.

In the case of `rust-zmq`, you need to add the following attribute to the `pkgs.rustBuilder.makePackageSet'` function call in your `default.nix` and rebuild:

```nix
localPatterns = [
  ''^(src|tests|build)(/.*)?''
  ''[^/]*\.(rs|toml)$''
];
```

I'm pretty sure this should resolve the issue. Please report back in the thread if there are further problems!

**Comment by cryptoquick** [comment]
@ebkalderon Does localPatterns also work on items outside the repo? `zmq-sys` is looking for `libzmq` which is registered to `pkg-config` by `nixpkgs.zeromq`. We just need to provide it to a specific derivation. It works when we hand-edit this into the following to the buildDependencies in the Cargo.nix:
```nix
zeromq = (import <nixpkgs> { }).zeromq;
```

**Comment by ebkalderon** [comment]
`localPatterns` is not intended to be used in this way, and also the `Cargo.nix` file is not supposed to be edited directly. If you would like to include additional derivations from Nixpkgs required to build certain Crates.io crates, you will need to provide a _package override_ through the `packageOverrides` argument to `makePackageSet'` in your `default.nix` file. See [examples/2-bigger-project](https://github.com/tenx-tech/cargo2nix/tree/master/examples/2-bigger-project) for details on this argument, and [overlay/overrides.nix](https://github.com/tenx-tech/cargo2nix/blob/master/overlay/overrides.nix) for examples of real package overrides which come bundled by default with `cargo2nix`.

As described in the tutorial, if left unspecified, the `packageOverrides` argument defaults to:

```nix
packageOverrides = pkg: pkgs.rustBuilder.overrides.all;
```

`rustBuilder.overrides.all` is an array containing a list of package overrides which bundle e.g. the `pkgs.pkg-config` derivation with the `pkg-config` crate, and they propagate the system dependencies up the Cargo dependency chain to every downstream crate that relies on it.

In your specific case, you will need to edit the `default.nix` and add/replace the `packageOverrides` argument with:

```nix
packageOverrides =
  let
    zmq-sys = pkgs.rustBuilder.rustLib.makeOverride {
      name = "zmq-sys";
      overrideAttrs = drv: {
        propagatedBuildInputs = drv.propagatedBuildInputs or [ ] ++ [ pkgs.zeromq ];
      };
    };
  in
    pkgs: pkgs.rustBuilder.overrides.all ++ [ zmq-sys ];
```

This will ensure that `zmq-sys`, whenever it is built, will propagate its `pkgs.zeromq` build dependency to whatever downstream Rust crates depend on it. Since the `zmq-sys` crate already depends indirectly on the `pkg-config` crate, it is already leveraging the `pkg-config` package override included by default with `cargo2nix` in a similar manner, eliminating the need to specify `pkgs.pkg-config` explicitly in the override shown above.

Our general policy is that `cargo2nix` should be able to build any crate from Crates.io out-of-the-box without manually specifying any package overrides ([CONTRIBUTING.md](https://github.com/tenx-tech/cargo2nix/blob/master/CONTRIBUTING.md#1-failure-to-build-due-to-a-missing-system-dependency)), and this seems like a pretty good case of a common Rust crate which requires a system dependency to build. These package overrides are shipped in the aforementioned `overlay/overrides.nix` file.

We would gladly take a PR adding the `zmq-sys` package override shown above to `overlay/overrides.nix`, if you're up for contributing something! It will be included in the next release so you don't have to specify the override manually and things should "Just Work." 😄

**Comment by cryptoquick** [comment]
@ebkalderon That worked! Thanks!

As for giving back, I'd be nervous contributing to a project I have such little experience with, and that would affect a large part of the Rust-Nix community, but, I'd hope you wouldn't let me screw it up. You've been so helpful, so I'll give it a try. :)

**Comment by ebkalderon** [comment]
Awesome! Please don't hesitate at all to throw a PR our way, even a small one. It'll be thoroughly reviewed before merging, so no worries. 😊

**Comment by bsima** [comment]
Thanks for the quick help @ebkalderon! It is very much appreciated :) I guess I would have expected cargo2nix to read the Cargo.toml and figure out to include the `build` dir automatically, but if that's not in the feature scope then that's fine too. Either @cryptoquick or I will submit a patch for `zmq-sys` soon.

**Comment by ebkalderon** [comment]
Sounds great, @bsima! I'm eagerly awaiting the PR. Feel free to ping me if you need any mentoring on it. 👍 

Yeah, we've considered relying on the `include` and `exclude` keys in the `Cargo.toml` for filtering source files before, but ultimately, we've been pretty hesitant to do so because most common crates do not include those keys and therefore crate root directories can potentially get very heavy (especially if there are symlinks to the Nix store or leftover `target` directories in the tree). To be on the safe side, and to avoid bloating the Nix store and accidentally exhausting the users' disk space, we deny all files by default and require explicit whitelisting with `localPatterns`. There might be a potential solution to this, though. We're open to any suggestions, of course!
