### ISSUE TITLE
Provide more default values in overlay

### ISSUE THREAD

**Issue by ebkalderon** [tenx-tech/cargo2nix#19]
Considering the high complexity of the `default.nix` referenced by most projects, it would be nice if we provided more default values in the `cargo2nix` overlay to reduce the initial boilerplate. Some examples include:

1. Restoring `<nixpkgs>` as the default, if left unspecified. This [used to be the default value](https://github.com/tenx-tech/cargo2nix/pull/17/files#diff-5712e736e0de6ba170577f8472c398e9R2), but was changed to help cross-compilation of `cargo2nix` specifically. The `nixpkgs.nix` isn't needed for projects using `cargo2nix` as a build system, so maybe the generated `default.nix` would simply use `<nixpkgs>` as the default (see #18).
2. Importing the `cargo2nix` overlay could also re-export the `nixpkgs-mozilla` overlay, with the latest Rust stable selected as the default and `aarch64-unknown-linux-gnu` enabled, if left unspecified.
3. Common patched dependencies such as `openssl` and `macosFrameworks` could be re-exported from the overlay, if needed.
4. `resolveResponse` and `rustPackagesWithResolve` could have a default value for simple cases where manual resolution isn't necessary or impractical for a given project.

Any thoughts, @dingxiangfei2009?

**Comment by dingxiangfei2009** [comment]
1. I think this is a fair point, especially when I as a user just want to use whichever `<nixpkgs>` specified by the system.

2. The Mozilla overlay can be (?) specified as an additional input to the `cargo2nix` overlay function. Adding `aarch64-unknown-linux-gnu` is very welcomed, since this will highlight that this overlay is capable of handling cross-compilation.

3. Very welcomed! Tired of specifying it in every projects I am working on that has remotely depended on cryptography

4. Yes please. In fact, the expression in `default.nix` is canonical? I cannot draw useful variants or abstraction so far from my experience.

**Comment by workflow** [comment]
@ebkalderon How would you assess the current state?

**Comment by ebkalderon** [comment]
The most recent version of `overlay/overrides.nix` now provides a very comprehensive list of default overrides for packages, and all of the bullet points in the issue description are either now included in that file or are no longer applicable, such as `cargo2nix resolve` and `resolveResponse` which don't exist anymore. The `default.nix` has been whittled down to such a lightweight and small size that I believe this issue can be safely closed.
