### ISSUE TITLE
Rewrite with Async/Await

### ISSUE THREAD

**Issue by dingxiangfei2009** [tenx-tech/cargo2nix#31]
Looks like `async`/`await` is stable in Rust `1.39.0`. :confetti_ball: 

There is a possibility that we can switch to `async`/`await` as well as `std::future`. This will depends on whether we want to switch to `1.39.0`.

This can be assigned to me if :hand: is needed.

**Comment by ebkalderon** [comment]
Since the resolve request functionality [was removed in 0.4.0](https://github.com/tenx-tech/cargo2nix/releases/tag/v0.4.0) and the `cargo2nix` command only parses files and prints text to stdout now, I don't believe this is necessary anymore. `cargo2nix` no longer needs to respond to queries and would no longer benefit from a rewrite to async/await.
